UPDATE MANAGER
SET salary = salary + (salary*10)/100;

DELETE FROM MANAGER
WHERE SALARY<2750;

ALTER TABLE EMP RENAME COLUMN ename to NAME;
ALTER TABLE EMP RENAME COLUMN sal to SALARY;
SELECT NAME,SALARY*12 FROM EMP;

SELECT name || ',' || job AS CONCAT
FROM EMP;

SELECT name FROM EMP WHERE job='CLERK';

SELECT name FROM EMP WHERE empno= 7369 OR 7839 OR 7934 OR 7788;

SELECT name FROM EMP WHERE job<>'MANAGER';

SELECT name FROM EMP WHERE
hiredate BETWEEN 
'30-JUN-81' AND '31-DEC-81';

SELECT DISTINCT job FROM EMP;

SELECT name FROM EMP WHERE COMM<>'';


SELECT name
From EMP
Where name like '%S'OR 'S%';


SELECT name
From EMP
Where name like '_I%';

SELECT name,JOB,dept,hiredate FROM EMP ORDER BY hiredate ASC;

SELECT empno,name,job,SALARY*12 FROM EMP ORDER BY salary DESC;



UPDATE DEPT
SET loc='CHICAGO' WHERE deptno=30;
COMMIT TRANSACTION;

UPDATE DEPT
SET loc='BOSTON' WHERE deptno=40;
SAVEPOINT update_over;
ROLLBACK TO update_over;